name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: "Auto-assign issue"
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: hatuna-827, K10-K10, karencaya, kinoto0103, mochi-k18, rotarymars, SakaYq4875, Shirym-min, utsukushiioto0816-tech
          numOfAssignee: 9
